### ISSUE TITLE
Getting error relating to unknown revision

### ISSUE THREAD

**Issue by garethhowell** [saltstack-formulas/gitolite-formula#2]
It's a fork of this rep, but unchanged other than repository_url
When I try to run this state I get the following:

`

          ID: /home/git/gitolite
    Function: git.latest
        Name: https://github.com/garethhowell/gitolite-formula.git
      Result: False
     Comment: No revision matching 'v3.6.1' exists in the remote repository
     Started: 19:50:56.576628
    Duration: 676.42 ms
     Changes:   
`

**Comment by mostafahussein** [comment]
The git url refers to this repo https://github.com/sitaramc/gitolite not the formula's repo, so you may fork the [gitolite](https://github.com/sitaramc/gitolite) itself then update your formula with your own link.

**Comment by garethhowell** [comment]
Sorry, a typo in my OP. It is the repository_url I updated, not the revision_url. I've updated the issue.
Thanks for pointing it out.

**Comment by mostafahussein** [comment]
My point is you should use this url: https://github.com/sitaramc/gitolite as a repository_url or you may fork it and use the forked version

**Comment by garethhowell** [comment]
I think I've got it now. I was thinking that the repository_url was intended to point to the formula repo, not the gitolite repo.

**Comment by mostafahussein** [comment]
Glad you figure it out , I will close this issue for now. Thanks
